services:
  jenkins:
    image: jenkins/jenkins:jdk17
    restart: always
    user: root
    container_name: jenkins
    volumes:
      - "/data/jenkins/jenkins_home:/var/jenkins_home"
      - "/usr/local/bin/helm:/usr/local/bin/helm"
      - "/usr/bin/argocd:/usr/bin/argocd"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8081:8080"
      - "50000:50000"
