services:
  python-codechat-2:
    image: docker-dev.x2bee.com/ai-labs/code-assistant-python-3.11.9-slim:1
    container_name: python-codechat-2
    environment:
      - GIT_USERNAME=jeongzmin%40plateer.com
      - GIT_PASSWORD=456456aa
      - GIT_URL=gitlab.x2bee.com/tech-team-gpt/codechatbotforx2beedemo.git
      - PYTHON_SCRIPT=flask_app.py
      - PROJECT_DIR=/codechatbotforx2beedemo
    ports:
      - "8502:8501"
    volumes:
      - ./git-script.sh:/git-script.sh
      - ./run-script.sh:/run-script.sh
      - /data/python-codechat-2-data:/home/codechatbotforx2beedemo
    entrypoint:
      - /bin/sh
      - -c
      - |
        chmod +x /git-script.sh
        chmod +x /run-script.sh
        /git-script.sh
        /run-script.sh
        tail -f /dev/null
