services:
  opensearch-node:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=X2commerce!1
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - plugins.security.ssl.http.enabled=false
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    volumes:
      - ./opensearch/opensearch-plungins-install.sh:/usr/share/opensearch/opensearch-plungins-install.sh
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/share/opensearch/opensearch-plungins-install.sh
        /usr/share/opensearch/opensearch-docker-entrypoint.sh

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://192.168.2.246:9200
        #- OPENSEARCH_HOSTS=http://opensearch-node:9200
    ports:
      - "5601:5601"
    networks:
      - opensearch-net

networks:
  opensearch-net:
