services:
  code-assistant-python:
    container_name: ${CONTAINER_NAME} #code-assistant-python-plateer
    build:
      context: .
    env_file:
      - ${ENV_FILE_PATH} # ./env/.plateer.env
    ports:
      - "${HOST_PORT:-8502}:${CONTAINER_PORT:-8501}"
    volumes:
      - ./script:/script
      - ../data/${CONTAINER_NAME}:/home/${CONTAINER_NAME}
    entrypoint:
      - /bin/sh
      - -c
      - |
        chmod 755 /script/permissions.sh
        /script/permissions.sh
        /script/git-script.sh
        /script/entrypoint.sh
