services:
  nifi:
    image: apache/nifi:1.26.0
    container_name: nifi
    environment:
      - NIFI_WEB_HTTP_PORT=8084
      - TZ=Asia/Seoul
    ports:
      - "8084:8084"
    restart: always
    user: "root"
    volumes:
      - "./nifi-volumes/etc:/opt/nifi/nifi-1.26.0/etc"
      - "./nifi-volumes/scripts:/opt/nifi/nifi-1.26.0/sh"
        #- "./nifi-volumes/conf:/opt/nifi/nifi-current/conf"
      - "./nifi-volumes/database_repository:/opt/nifi/nifi-current/database_repository"
      - "./nifi-volumes/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository"
      - "./nifi-volumes/content_repository:/opt/nifi/nifi-current/content_repository"
      - "./nifi-volumes/provenance_repository:/opt/nifi/nifi-current/provenance_repository"
      - "./nifi-volumes/state:/opt/nifi/nifi-current/state"
