services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    volumes:
      - "/data/nexus:/sonatype-work"
    ports:
      - "8082:8081"
      - "8085:8085"
      - "5000:5000"
