x-jenkins-environment: &jenkins-environment
  ARGOCD_SERVER: "192.168.2.172:10030"
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: "X2commerce!1"

services:
  jenkins:
    image: jenkins/jenkins:jdk17
    restart: always
    user: root
    container_name: jenkins
    environment:
      <<: *jenkins-environment
      TZ: Asia/Seoul
    volumes:
      - "/data/jenkins_home:/var/jenkins_home"
      - "/usr/local/bin/helm:/usr/local/bin/helm"
      - "/usr/bin/argocd:/usr/bin/argocd"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-install.sh:/usr/local/bin/init-install.sh"
    ports:
      - "8081:8080"
      - "50000:50000"
    entrypoint:
      - /bin/sh
      - -c
      - |
        chmod 755 /usr/local/bin/init-install.sh  # 실행 권한 설정
        /usr/local/bin/init-install.sh
        chmod 644 /usr/local/bin/init-install.sh  # 권한 원복
        /bin/tini -- /usr/local/bin/jenkins.sh  # Jenkins 기본 실행 명령어

        