x-opensearch-environment: &opensearch-environment
  bootstrap.memory_lock: "true"
  OPENSEARCH_JAVA_OPTS: "-Xms4g -Xmx4g"
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "X2commerce!1"
  plugins.security.ssl.http.enabled: false

services:
  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      <<: *opensearch-environment
      node.name: opensearch-node2
      network.host: 0.0.0.0
      plugins.security.disabled: "true"
      cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2
      discovery.seed_hosts: 192.168.2.150:9300,192.168.2.151:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./conf/opensearch-plugin-install.sh:/usr/share/opensearch/opensearch-plugin-install.sh
    network_mode: "host"
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/share/opensearch/opensearch-plugin-install.sh
        /usr/share/opensearch/opensearch-docker-entrypoint.sh

volumes:
  opensearch-data2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tech/data/opensearch-dir/data-d2
