version: '3.8'

services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://192.168.2.150:9200","https://192.168.2.151:9200"]' # 각 노드의 IP 주소 입력
    networks:
      - opensearch-net

networks:
  opensearch-net:
    external: true
