x-opensearch-environment: &opensearch-environment
  bootstrap.memory_lock: "true"
  OPENSEARCH_JAVA_OPTS: "-Xms4g -Xmx4g"
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "X2commerce!1"
  plugins.security.ssl.http.enabled: false

services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      <<: *opensearch-environment
      cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2
      node.name: opensearch-node1
      network.host: 0.0.0.0
      plugins.security.disabled: "true"
      discovery.seed_hosts: 192.168.2.150:9300,192.168.2.151:9300
      OPENSEARCH_SECURITY_ENABLED: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./conf/opensearch-plugin-install.sh:/usr/share/opensearch/opensearch-plugin-install.sh
    network_mode: "host"
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/share/opensearch/opensearch-plugin-install.sh
        /usr/share/opensearch/opensearch-docker-entrypoint.sh

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    network_mode: "host"
    environment:
      OPENSEARCH_HOSTS: '["http://192.168.2.150:9200","http://192.168.2.151:9200"]' # 각 노드의 IP 주소 입력
      OPENSEARCH_SECURITY_ENABLED: "false"
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'

volumes:
  opensearch-data1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tech/data/opensearch-dir/data-d1
