version: "3.8"

x-opensearch-environment: &opensearch-environment
  cluster.name: opensearch-cluster
  bootstrap.memory_lock: "true"
  OPENSEARCH_JAVA_OPTS: "-Xms16g -Xmx16g"
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "X2commerce!1"
  plugins.security.ssl.http.enabled: "false"

services:
  opensearch-manager:
    image: opensearchproject/opensearch:3
    container_name: opensearch-manager
    environment:
      <<: *opensearch-environment
      node.name: opensearch-manager
      node.roles: '["cluster_manager"]'
      discovery.seed_hosts: opensearch-manager,opensearch-writer,opensearch-reader
      cluster.initial_cluster_manager_nodes: opensearch-manager,opensearch-writer,opensearch-reader
    deploy:
      resources:
        limits:
          memory: 24g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data-m1:/usr/share/opensearch/data
      - ./conf/opensearch-plugin-install.sh:/usr/share/opensearch/opensearch-plugin-install.sh
    networks:
      - opensearch-net
    restart: always
    command: >
      sh -c "chmod +x /usr/share/opensearch/opensearch-plugin-install.sh &&
            /usr/share/opensearch/opensearch-plugin-install.sh &&
            /usr/share/opensearch/opensearch-docker-entrypoint.sh"

  opensearch-writer:
    image: opensearchproject/opensearch:3
    container_name: opensearch-writer
    environment:
      <<: *opensearch-environment
      node.name: opensearch-writer
      node.attr.role: writer
      discovery.seed_hosts: opensearch-manager,opensearch-writer,opensearch-reader
      cluster.initial_cluster_manager_nodes: opensearch-manager,opensearch-writer,opensearch-reader
    deploy:
      resources:
        limits:
          memory: 24g
        reservations:
          memory: 16g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./conf/opensearch-plugin-install.sh:/usr/share/opensearch/opensearch-plugin-install.sh
    networks:
      - opensearch-net
    restart: always
    command: >
      sh -c "chmod +x /usr/share/opensearch/opensearch-plugin-install.sh &&
            /usr/share/opensearch/opensearch-plugin-install.sh &&
            /usr/share/opensearch/opensearch-docker-entrypoint.sh"

  opensearch-reader:
    image: opensearchproject/opensearch:3
    container_name: opensearch-reader
    environment:
      <<: *opensearch-environment
      node.name: opensearch-reader
      node.attr.role: reader
      discovery.seed_hosts: opensearch-manager,opensearch-writer,opensearch-reader
      cluster.initial_cluster_manager_nodes: opensearch-manager,opensearch-writer,opensearch-reader
    deploy:
      resources:
        limits:
          memory: 24g
        reservations:
          memory: 16g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./conf/opensearch-plugin-install.sh:/usr/share/opensearch/opensearch-plugin-install.sh
    networks:
      - opensearch-net
    restart: always
    command: >
      sh -c "chmod +x /usr/share/opensearch/opensearch-plugin-install.sh &&
            /usr/share/opensearch/opensearch-plugin-install.sh &&
            /usr/share/opensearch/opensearch-docker-entrypoint.sh"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-reader:9200"]'
    networks:
      - opensearch-net
    restart: always

volumes:
  opensearch-data1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/opensearch-dir/data-d1
  opensearch-data2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/opensearch-dir/data-d2
  opensearch-data-m1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/opensearch-dir/data-m1

networks:
  opensearch-net: